// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwg6MKfZD4w5c-UVmTH4W1-UZcvHYawZo',
    appId: '1:228523048206:web:ba82160aeb7fc79db22b5f',
    messagingSenderId: '228523048206',
    projectId: 'bodlebodle2-2e595',
    authDomain: 'bodlebodle2-2e595.firebaseapp.com',
    storageBucket: 'bodlebodle2-2e595.firebasestorage.app',
    measurementId: 'G-C81VB9VMF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf2cqRFpnSVgaqWn6kzoiJO8n-0uOKi9A',
    appId: '1:228523048206:android:7da4a427099db2a0b22b5f',
    messagingSenderId: '228523048206',
    projectId: 'bodlebodle2-2e595',
    storageBucket: 'bodlebodle2-2e595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb2x8WESvNne2aGOzT4VHYwrgfXpi9uAs',
    appId: '1:228523048206:ios:7eba55169c6b92deb22b5f',
    messagingSenderId: '228523048206',
    projectId: 'bodlebodle2-2e595',
    storageBucket: 'bodlebodle2-2e595.firebasestorage.app',
    iosBundleId: 'com.example.bodlebodle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb2x8WESvNne2aGOzT4VHYwrgfXpi9uAs',
    appId: '1:228523048206:ios:7eba55169c6b92deb22b5f',
    messagingSenderId: '228523048206',
    projectId: 'bodlebodle2-2e595',
    storageBucket: 'bodlebodle2-2e595.firebasestorage.app',
    iosBundleId: 'com.example.bodlebodle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwg6MKfZD4w5c-UVmTH4W1-UZcvHYawZo',
    appId: '1:228523048206:web:8fa84796a43a6358b22b5f',
    messagingSenderId: '228523048206',
    projectId: 'bodlebodle2-2e595',
    authDomain: 'bodlebodle2-2e595.firebaseapp.com',
    storageBucket: 'bodlebodle2-2e595.firebasestorage.app',
    measurementId: 'G-83FCS9ESJ0',
  );
}
